### ISSUE TITLE
[BUG] 插件面板消失

### ISSUE THREAD

**Issue by if1y** [yn-zxj/Typecho_Admin_Theme#1]
<img width="135" alt="Screenshot_2020-03-11_224544" src="https://user-images.githubusercontent.com/32222791/76429633-45a28f80-63ea-11ea-92ca-0565cdce4c4a.png">

如图，Access 和评论邮件提醒的独立菜单，在大佬的主题中都消失了。

**Comment by yn-zxj** [comment]
我也不是专业的 ，我尝试着解决下，如果你有办法，可以联系我，谢谢！

**Comment by yn-zxj** [comment]
已经修复！

**Comment by xiamuguizhi** [comment]
@yn-zxj 当前版本：  这里建议下次添加个 版本信息吧  强迫症表示 很在意 因为 空白 ！！

**Comment by yn-zxj** [comment]
> @yn-zxj 当前版本： 这里建议下次添加个 版本信息吧 强迫症表示 很在意 因为 空白 ！！

这里留着是显示官方版本的更新信息   但是目前官方版本这里有问题  官方无法显示，我也没法  要么你自己随便改改或者删除 或者强忍着吧
