### ISSUE TITLE
menu报错 

### ISSUE THREAD

**Issue by trunk1011** [yn-zxj/Typecho_Admin_Theme#2]
![image](https://user-images.githubusercontent.com/63278017/78680855-98eefb80-791e-11ea-9099-52c362611c52.png)

**Comment by yn-zxj** [comment]
你是部署在本地吗？

**Comment by trunk1011** [comment]
我弄在了服务器里面&nbsp;&nbsp;
&nbsp;

姓名：丁一恺
 班级：网络1714
 学号：1708030407


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lalis"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上10:33
收件人: "yn-zxj/Typecho_Admin_Theme"<Typecho_Admin_Theme@noreply.github.com&gt;; 
抄送: "飞翔的雷杰"<1352000052@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yn-zxj/Typecho_Admin_Theme] menu报错  (#2)





 
你是部署在本地吗？

**Comment by trunk1011** [comment]
您qq多少 方便的话qq聊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lalis"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上10:33
收件人:&nbsp;"yn-zxj/Typecho_Admin_Theme"<Typecho_Admin_Theme@noreply.github.com&gt;;
抄送:&nbsp;"飞翔的雷杰"<1352000052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yn-zxj/Typecho_Admin_Theme] menu报错  (#2)





 
你是部署在本地吗？

**Comment by yn-zxj** [comment]
331134138
